apiVersion: v2
name: sonarqube
description: SonarQube Community Edition — NNT homelab
type: application
version: 1.0.1

dependencies:
  - name: sonarqube
    version: "2026.2.1"
    repository: https://SonarSource.github.io/helm-chart-sonarqube
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
